### ISSUE TITLE
Gold counter doesn't fade out with the rest of the UI

### ISSUE THREAD

**Issue by Vultraz** [frogatto/frogatto#459]
If you have gold when exiting Frogatto's house for the first time, the giant gold counter is still visible as the scene fades in.

**Comment by rkettering** [comment]
Fixed in 9495f1d8cd4575bd72ce23fd4e59756c19c94ab6

**Comment by Vultraz** [comment]
This is still an issue. In fact, even when the counter hides before exiting the house, it reappears when exiting in the cutscene.

**Comment by rkettering** [comment]
The main beef here is the text, itself, isn't fading out, and I think it's because `text()` calls in general don't do that.

**Comment by rkettering** [comment]
Partly fixed in:  aef80f41b    (The issue fixed here is the timing that's used to trigger it.)

**Comment by rkettering** [comment]
Fixed in 55d22a5ac, using the `text_alpha` property.
